import express from "express";
import multer from "multer";
import dotenv from "dotenv";
import { GoogleGenAI, Type } from "@google/genai";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.static("public"));
app.use(express.json({ limit: "10mb" }));

const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 10 * 1024 * 1024
  }
});

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY
});

app.post("/api/generate", upload.single("image"), async (req, res) => {
  try {
    const studentId = (req.body.studentId || "126106043").trim();
    const questions = (req.body.questions || "").trim();
    const count = Math.max(1, Math.min(Number(req.body.count || 1), 20));

    if (!questions && !req.file) {
      return res.status(400).json({
        error: "Please enter questions or upload an assignment image."
      });
    }

    const prompt = `
You are a C programming assignment generator for first-year engineering students.

Student ID: ${studentId}
Number of programs required: ${count}

Generate exactly ${count} separate C programs based on the assignment questions.

Rules:
- Use standard C only.
- Every program must compile independently.
- Every program must contain main().
- Include return 0;.
- Keep the code beginner-friendly.
- Do not use C++.
- Do not combine questions.
- Do not include Markdown code fences.
- Return exactly ${count} programs.

For each program provide:
1. question
2. code

The filename will be generated by the server as:
${studentId}_1.c
${studentId}_2.c
${studentId}_3.c
etc.

Assignment questions:
${questions}
`;

    const contents = [];

    contents.push({
      text: prompt
    });

    if (req.file) {
      contents.push({
        inlineData: {
          data: req.file.buffer.toString("base64"),
          mimeType: req.file.mimetype
        }
      });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: [
        {
          role: "user",
          parts: contents
        }
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            programs: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  question: {
                    type: Type.STRING
                  },
                  code: {
                    type: Type.STRING
                  }
                },
                required: ["question", "code"]
              }
            }
          },
          required: ["programs"]
        }
      }
    });

    const text = response.text;

    if (!text) {
      throw new Error("Gemini returned an empty response.");
    }

    const data = JSON.parse(text);

    if (!data.programs || !Array.isArray(data.programs)) {
      throw new Error("Invalid Gemini response.");
    }

    const programs = data.programs.slice(0, count).map((program, index) => ({
      filename: `${studentId}_${index + 1}.c`,
      question: program.question || `Question ${index + 1}`,
      code: String(program.code || "").trim()
    }));

    if (programs.length === 0) {
      throw new Error("No programs were generated.");
    }

    res.json({ programs });

  } catch (error) {
    console.error("Generation error:", error);

    res.status(500).json({
      error: error.message || "Something went wrong."
    });
  }
});

app.get("/", (req, res) => {
  res.sendFile("index.html", {
    root: "public"
  });
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`C Assignment Generator running on port ${PORT}`);
});
